language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: cAdxR+JT/qHtsDIeUX3TZYFEvB4URlarimDeZLi/DThuFBUt4RDlZPTffqNJFT6e7AHNlMeUfBnBjXcsbKpAQB/svx/el0c7fSyhznsE/KkWQHfzFYp1z9uW+Qgbi2TFNysMnAeOX88I6zZDuLnqKBwWtvjYtYkyHyiCnT4imgoF891krZuw5J7LzbR1WmLpNsFKOLEllKKNgT5B/aY1etfXzJZS3eR89pDXQPs4kAFtYsYyuAFjj2TfX9oWGDFVmmv45siBUGizfWE/PF4+CUtTRIvbyUTy9NAJGDiCkUvlLtgeDV5DdkBiYlVyzQWISZaJ9ttvo/3kXTpbVIUMXt5a1NYvkbEEUgRPhYD8AJE28aJ6WtsILvFhXMYV9n6wQY7KRubGjRVTCqsH7OhpV+YJYBWxlgU+rk/H8JTCXCaMRJecouY0f5yH/q/mB6RaIEhWKtPgOjRew2adR9AtrUvDp+dNskbFA1BPodOwKNDHkFPXr6/lpjGuQSJ2zR6mBuOq0aR3zFj8aL7NEzwqbsLoMaLPY7m1LDZXqP+MCFOEAB72FqGps7N0ZQ9K3wskcl/UPPmn2Bo205GgHEDTYffnl5pOZDQmWT240QBEbDrMa00skmInaJiN5z5/f4yGBP1iQuZx3qenB3H1nUknWoa67tt2khaZ3KDRWxZ4fi0=
  app: linda-brent-dec22-integration-testing
  on:
    repo: thinkful-ei17/linda-brent-dec22-integration-testing
